"""Property tests for CLI argument parsing.

Feature: cli-entry-point, Property 1: Argument parsing round-trip

**Property 1: Argument parsing round-trip** — For any valid combination of
required arguments (input_file path, package, template, budgetcode, year) and
optional arguments (output path, format), parsing the argument list should
produce a namespace where each attribute exactly matches the provided value,
and omitted optional arguments should have their documented defaults
(format defaults to "csv", output defaults to None).

**Validates: Requirements 1.1, 1.2, 1.3, 1.4**
"""

from __future__ import annotations

from hypothesis import given, settings
from hypothesis import strategies as st

from src.cli import build_parser


# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------

# Positional arg strings: non-empty, no leading dash, no whitespace
_positional_str = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N", "P"), blacklist_characters="-"),
    min_size=1,
    max_size=30,
).filter(lambda s: not s.startswith("-") and len(s.strip()) > 0)

# File path-like strings for input_file and output
_path_str = st.from_regex(r"[A-Za-z0-9_./]{1,40}", fullmatch=True).filter(
    lambda s: not s.startswith("-")
)


@st.composite
def cli_argv(draw: st.DrawFn):
    """Generate a valid argv list and the expected parsed values."""
    input_file = draw(_path_str)
    package = draw(_positional_str)
    template = draw(_positional_str)
    budgetcode = draw(_positional_str)
    year = draw(st.integers(min_value=-9999, max_value=9999))

    include_output = draw(st.booleans())
    include_format = draw(st.booleans())

    argv = [
        input_file,
        package,
        template,
        "--budgetcode", budgetcode,
        "--year", str(year),
    ]

    expected_output = None
    expected_format = "csv"

    if include_output:
        output_path = draw(_path_str)
        argv.extend(["--output", output_path])
        expected_output = output_path

    if include_format:
        fmt = draw(st.sampled_from(["csv", "excel"]))
        argv.extend(["--format", fmt])
        expected_format = fmt

    expected = {
        "input_file": input_file,
        "package": package,
        "template": template,
        "budgetcode": budgetcode,
        "year": year,
        "output": expected_output,
        "format": expected_format,
    }

    return argv, expected


# ---------------------------------------------------------------------------
# Property test
# ---------------------------------------------------------------------------

@given(data=cli_argv())
@settings(max_examples=100, deadline=None)
def test_property_1_argument_parsing_round_trip(data):
    """Parsing a valid argv produces a namespace matching every provided value,
    with documented defaults for omitted optional arguments.

    **Validates: Requirements 1.1, 1.2, 1.3, 1.4**
    """
    argv, expected = data
    parser = build_parser()
    ns = parser.parse_args(argv)

    # Required positional arguments (Req 1.1)
    assert ns.input_file == expected["input_file"]
    assert ns.package == expected["package"]
    assert ns.template == expected["template"]

    # Required named arguments (Req 1.2)
    assert ns.budgetcode == expected["budgetcode"]
    assert ns.year == expected["year"]

    # Optional output path (Req 1.3) — defaults to None
    assert ns.output == expected["output"]

    # Optional format (Req 1.4) — defaults to "csv"
    assert ns.format == expected["format"]


# ---------------------------------------------------------------------------
# Feature: cli-entry-point, Property 3: Invalid file bytes produce exit code 1
# ---------------------------------------------------------------------------

import argparse
import sys
import tempfile
import os
from io import StringIO

from src.cli import run


@given(raw_bytes=st.binary(min_size=0, max_size=4096))
@settings(max_examples=100, deadline=None)
def test_property_3_invalid_file_bytes_produce_exit_code_1(raw_bytes):
    """For any byte sequence that is not a valid .xlsx file, run() should
    return exit code 1 and write a parse error message to stderr.

    **Validates: Requirements 2.3, 6.2**
    """
    # Write the generated bytes to a temporary file
    fd, tmp_path = tempfile.mkstemp(suffix=".xlsx")
    try:
        os.write(fd, raw_bytes)
        os.close(fd)

        # Build a Namespace with all attributes that run() accesses
        args = argparse.Namespace(
            list_packages=False,
            list_templates=None,
            input_file=tmp_path,
            package="twinfield",
            template="budget",
            budgetcode="TEST",
            year=2025,
            output=None,
            format="csv",
            verbose=False,
            quiet=False,
        )

        # Capture stderr
        old_stderr = sys.stderr
        sys.stderr = captured = StringIO()
        try:
            exit_code = run(args)
        finally:
            sys.stderr = old_stderr

        stderr_output = captured.getvalue()

        assert exit_code == 1, (
            f"Expected exit code 1 for invalid bytes, got {exit_code}"
        )
        assert "Error:" in stderr_output, (
            f"Expected 'Error:' in stderr, got: {stderr_output!r}"
        )
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)


# ---------------------------------------------------------------------------
# Feature: cli-entry-point, Property 2: Non-existent file paths produce exit code 1
# ---------------------------------------------------------------------------


@given(file_name=st.text(
    alphabet=st.characters(whitelist_categories=("L", "N"), blacklist_characters="/\\"),
    min_size=1,
    max_size=40,
))
@settings(max_examples=100, deadline=None)
def test_property_2_nonexistent_file_paths_produce_exit_code_1(file_name):
    """For any file path string that does not correspond to an existing file
    on disk, the CLI run() function should return exit code 1 and write an
    error message containing "not found" to stderr.

    **Validates: Requirements 2.2, 6.2**
    """
    # Build a path under a non-existent directory to guarantee it doesn't exist
    nonexistent_path = os.path.join(
        tempfile.gettempdir(), "nonexistent_kiro_test_dir", file_name + ".xlsx"
    )
    assert not os.path.exists(nonexistent_path), (
        f"Generated path unexpectedly exists: {nonexistent_path}"
    )

    # Build a Namespace with all attributes that run() accesses
    args = argparse.Namespace(
        list_packages=False,
        list_templates=None,
        input_file=nonexistent_path,
        package="twinfield",
        template="budget",
        budgetcode="TEST",
        year=2025,
        output=None,
        format="csv",
        verbose=False,
        quiet=False,
    )

    # Capture stderr
    old_stderr = sys.stderr
    sys.stderr = captured = StringIO()
    try:
        exit_code = run(args)
    finally:
        sys.stderr = old_stderr

    stderr_output = captured.getvalue()

    assert exit_code == 1, (
        f"Expected exit code 1 for non-existent file, got {exit_code}"
    )
    assert "not found" in stderr_output.lower(), (
        f"Expected 'not found' in stderr, got: {stderr_output!r}"
    )


# ---------------------------------------------------------------------------
# Feature: cli-entry-point, Property 4: Invalid registry lookups list available alternatives
# ---------------------------------------------------------------------------

from unittest.mock import patch, MagicMock

from src.templates.registry import listPackages, listTemplates

# Known registry contents
_KNOWN_PACKAGES = listPackages()          # ["twinfield", "exact", "afas"]
_KNOWN_TEMPLATES = {pkg: listTemplates(pkg) for pkg in _KNOWN_PACKAGES}

# Strategy: arbitrary strings that are NOT valid package names
_invalid_package_name = st.text(min_size=1, max_size=50).filter(
    lambda s: s not in _KNOWN_PACKAGES
)

# Strategy: pick a valid package, then generate a template name NOT in its list
@st.composite
def _valid_package_invalid_template(draw):
    pkg = draw(st.sampled_from(_KNOWN_PACKAGES))
    tpl = draw(
        st.text(min_size=1, max_size=50).filter(
            lambda s, p=pkg: s not in _KNOWN_TEMPLATES[p]
        )
    )
    return pkg, tpl


def _make_args(package: str, template: str) -> argparse.Namespace:
    """Build a minimal Namespace for run() with the given package/template."""
    return argparse.Namespace(
        list_packages=False,
        list_templates=None,
        input_file="dummy.xlsx",
        package=package,
        template=template,
        budgetcode="TEST",
        year=2025,
        output=None,
        format="csv",
        verbose=False,
        quiet=False,
    )


def _run_with_mocked_imports(args: argparse.Namespace) -> tuple[int, str]:
    """Run the CLI with file-parsing functions mocked out so execution
    reaches the template lookup step. Returns (exit_code, stderr_text)."""
    mock_workbook = MagicMock()
    mock_budget_data = MagicMock()
    mock_mapping_config = MagicMock()

    # open(...).read() returns fake bytes — mock the builtin open
    fake_file = MagicMock()
    fake_file.read.return_value = b"fake"

    with patch("src.cli.parseExcelFile", return_value=mock_workbook), \
         patch("src.cli.extractBudgetData", return_value=mock_budget_data), \
         patch("src.cli.extractMappingConfig", return_value=mock_mapping_config), \
         patch("builtins.open", return_value=fake_file):
        old_stderr = sys.stderr
        sys.stderr = captured = StringIO()
        try:
            exit_code = run(args)
        finally:
            sys.stderr = old_stderr
    return exit_code, captured.getvalue()


@given(invalid_pkg=_invalid_package_name)
@settings(max_examples=100, deadline=None)
def test_property_4a_invalid_package_lists_available_packages(invalid_pkg):
    """For any string that is not a valid accounting package name, the CLI
    should exit with code 1 and stderr should contain every available
    package name.

    **Validates: Requirements 3.2, 6.2**
    """
    args = _make_args(package=invalid_pkg, template="budget")
    exit_code, stderr_output = _run_with_mocked_imports(args)

    assert exit_code == 1, (
        f"Expected exit code 1 for invalid package '{invalid_pkg}', got {exit_code}"
    )
    for pkg in _KNOWN_PACKAGES:
        assert pkg in stderr_output, (
            f"Expected package '{pkg}' in stderr, got: {stderr_output!r}"
        )


@given(data=_valid_package_invalid_template())
@settings(max_examples=100, deadline=None)
def test_property_4b_invalid_template_lists_available_templates(data):
    """For any valid package name paired with an invalid template name,
    the CLI should exit with code 1 and stderr should contain every
    available template name for that package.

    **Validates: Requirements 3.3, 6.2**
    """
    valid_pkg, invalid_tpl = data
    args = _make_args(package=valid_pkg, template=invalid_tpl)
    exit_code, stderr_output = _run_with_mocked_imports(args)

    assert exit_code == 1, (
        f"Expected exit code 1 for invalid template '{invalid_tpl}' "
        f"in package '{valid_pkg}', got {exit_code}"
    )
    for tpl in _KNOWN_TEMPLATES[valid_pkg]:
        assert tpl in stderr_output, (
            f"Expected template '{tpl}' in stderr, got: {stderr_output!r}"
        )


# ---------------------------------------------------------------------------
# Feature: cli-entry-point, Property 5: Transformation errors produce exit code 2
# ---------------------------------------------------------------------------

from src.core.types import TransformError, TransformSuccess, TabularData, UserParams


@st.composite
def _transform_error_message(draw):
    """Generate a non-empty error message for TransformError."""
    return draw(st.text(min_size=1, max_size=200).filter(lambda s: s.strip()))


@given(error_msg=_transform_error_message())
@settings(max_examples=100, deadline=None)
def test_property_5_transformation_errors_produce_exit_code_2(error_msg):
    """For any TransformError returned by run_budget_transformation, the CLI
    should exit with code 2 and write the error message to stderr.

    **Validates: Requirements 4.2, 6.3, 6.4**
    """
    mock_workbook = MagicMock()
    mock_budget_data = MagicMock()
    mock_mapping_config = MagicMock()
    mock_template = MagicMock()

    fake_file = MagicMock()
    fake_file.read.return_value = b"fake"

    transform_error = TransformError(message=error_msg)

    args = argparse.Namespace(
        list_packages=False,
        list_templates=None,
        input_file="dummy.xlsx",
        package="twinfield",
        template="budget",
        budgetcode="TEST",
        year=2025,
        output=None,
        format="csv",
        verbose=False,
        quiet=False,
    )

    with patch("src.cli.parseExcelFile", return_value=mock_workbook), \
         patch("src.cli.extractBudgetData", return_value=mock_budget_data), \
         patch("src.cli.extractMappingConfig", return_value=mock_mapping_config), \
         patch("src.cli.run_budget_transformation", return_value=transform_error), \
         patch("src.cli.getTemplate", return_value=mock_template), \
         patch("builtins.open", return_value=fake_file):
        old_stderr = sys.stderr
        sys.stderr = captured = StringIO()
        try:
            exit_code = run(args)
        finally:
            sys.stderr = old_stderr

    stderr_output = captured.getvalue()

    assert exit_code == 2, (
        f"Expected exit code 2 for TransformError, got {exit_code}"
    )
    assert error_msg in stderr_output, (
        f"Expected error message '{error_msg}' in stderr, got: {stderr_output!r}"
    )


# ---------------------------------------------------------------------------
# Feature: cli-entry-point, Property 8: Format argument maps to correct FileFormat
# ---------------------------------------------------------------------------

from src.core.types import FileFormat


@given(fmt=st.sampled_from(["csv", "excel", "CSV", "Excel", "EXCEL", "Csv"]))
@settings(max_examples=50, deadline=None)
def test_property_8_format_argument_maps_to_correct_file_format(fmt):
    """For any valid format string (case-insensitive), the CLI should map it
    to the correct FileFormat enum value and pass it to export_data.

    **Validates: Requirements 5.3, 5.4**
    """
    mock_workbook = MagicMock()
    mock_budget_data = MagicMock()
    mock_mapping_config = MagicMock()
    mock_template = MagicMock()
    mock_transformed = MagicMock()
    mock_transform_success = MagicMock(spec=TransformSuccess)
    mock_transform_success.data = mock_transformed

    fake_file = MagicMock()
    fake_file.read.return_value = b"fake"

    args = argparse.Namespace(
        list_packages=False,
        list_templates=None,
        input_file="dummy.xlsx",
        package="twinfield",
        template="budget",
        budgetcode="TEST",
        year=2025,
        output="/tmp/test_output.csv",
        format=fmt.lower(),  # argparse choices are lowercase
        verbose=False,
        quiet=False,
    )

    expected_format = FileFormat[fmt.upper()]

    with patch("src.cli.parseExcelFile", return_value=mock_workbook), \
         patch("src.cli.extractBudgetData", return_value=mock_budget_data), \
         patch("src.cli.extractMappingConfig", return_value=mock_mapping_config), \
         patch("src.cli.run_budget_transformation", return_value=mock_transform_success), \
         patch("src.cli.getTemplate", return_value=mock_template), \
         patch("src.cli.export_data", return_value=b"output") as mock_export, \
         patch("builtins.open", return_value=fake_file):
        old_stderr = sys.stderr
        sys.stderr = StringIO()
        try:
            exit_code = run(args)
        finally:
            sys.stderr = old_stderr

    assert exit_code == 0, f"Expected exit code 0, got {exit_code}"
    mock_export.assert_called_once()
    actual_format = mock_export.call_args[0][1]
    assert actual_format == expected_format, (
        f"Expected FileFormat.{expected_format.name} for format '{fmt}', "
        f"got FileFormat.{actual_format.name}"
    )


# ---------------------------------------------------------------------------
# Feature: cli-entry-point, Property 6: Stdout cleanliness on file output
# ---------------------------------------------------------------------------


@given(
    output_path=_path_str,
    fmt=st.sampled_from(["csv", "excel"]),
)
@settings(max_examples=100, deadline=None)
def test_property_6_stdout_cleanliness_on_file_output(output_path, fmt):
    """For any successful CLI run where an output file path is specified,
    stdout should be empty — all exported data should be written to the file,
    not to stdout.

    **Validates: Requirements 6.5**
    """
    mock_workbook = MagicMock()
    mock_budget_data = MagicMock()
    mock_mapping_config = MagicMock()
    mock_template = MagicMock()
    mock_transformed = MagicMock()
    mock_transform_success = MagicMock(spec=TransformSuccess)
    mock_transform_success.data = mock_transformed

    fake_input_file = MagicMock()
    fake_input_file.read.return_value = b"fake"

    fake_output_file = MagicMock()
    fake_output_file.__enter__ = MagicMock(return_value=fake_output_file)
    fake_output_file.__exit__ = MagicMock(return_value=False)

    call_count = 0

    def open_side_effect(*a, **kw):
        nonlocal call_count
        call_count += 1
        if call_count == 1:
            # First call: open(input_file, "rb").read()
            return fake_input_file
        # Second call: open(output, "wb") as context manager
        return fake_output_file

    args = argparse.Namespace(
        list_packages=False,
        list_templates=None,
        input_file="dummy.xlsx",
        package="twinfield",
        template="budget",
        budgetcode="TEST",
        year=2025,
        output=output_path,
        format=fmt,
        verbose=False,
        quiet=False,
    )

    with patch("src.cli.parseExcelFile", return_value=mock_workbook), \
         patch("src.cli.extractBudgetData", return_value=mock_budget_data), \
         patch("src.cli.extractMappingConfig", return_value=mock_mapping_config), \
         patch("src.cli.run_budget_transformation", return_value=mock_transform_success), \
         patch("src.cli.getTemplate", return_value=mock_template), \
         patch("src.cli.export_data", return_value=b"output data") as mock_export, \
         patch("builtins.open", side_effect=open_side_effect):
        old_stdout = sys.stdout
        old_stderr = sys.stderr
        sys.stdout = captured_stdout = StringIO()
        sys.stderr = StringIO()
        try:
            exit_code = run(args)
        finally:
            sys.stdout = old_stdout
            sys.stderr = old_stderr

    stdout_output = captured_stdout.getvalue()

    assert exit_code == 0, f"Expected exit code 0, got {exit_code}"
    assert stdout_output == "", (
        f"Expected empty stdout when output file is specified, "
        f"got: {stdout_output!r}"
    )


# ---------------------------------------------------------------------------
# Feature: cli-entry-point, Property 7: Quiet mode suppresses non-error stderr
# ---------------------------------------------------------------------------


@given(
    output_path=_path_str,
    fmt=st.sampled_from(["csv", "excel"]),
)
@settings(max_examples=100, deadline=None)
def test_property_7_quiet_mode_suppresses_non_error_stderr(output_path, fmt):
    """For any successful CLI run with the --quiet flag, stderr should be
    empty — no progress messages, no summary line.

    **Validates: Requirements 7.2**
    """
    mock_workbook = MagicMock()
    mock_budget_data = MagicMock()
    mock_mapping_config = MagicMock()
    mock_template = MagicMock()
    mock_transformed = MagicMock()
    mock_transform_success = MagicMock(spec=TransformSuccess)
    mock_transform_success.data = mock_transformed

    fake_input_file = MagicMock()
    fake_input_file.read.return_value = b"fake"

    fake_output_file = MagicMock()
    fake_output_file.__enter__ = MagicMock(return_value=fake_output_file)
    fake_output_file.__exit__ = MagicMock(return_value=False)

    call_count = 0

    def open_side_effect(*a, **kw):
        nonlocal call_count
        call_count += 1
        if call_count == 1:
            # First call: open(input_file, "rb").read()
            return fake_input_file
        # Second call: open(output, "wb") as context manager
        return fake_output_file

    args = argparse.Namespace(
        list_packages=False,
        list_templates=None,
        input_file="dummy.xlsx",
        package="twinfield",
        template="budget",
        budgetcode="TEST",
        year=2025,
        output=output_path,
        format=fmt,
        verbose=False,
        quiet=True,
    )

    with patch("src.cli.parseExcelFile", return_value=mock_workbook), \
         patch("src.cli.extractBudgetData", return_value=mock_budget_data), \
         patch("src.cli.extractMappingConfig", return_value=mock_mapping_config), \
         patch("src.cli.run_budget_transformation", return_value=mock_transform_success), \
         patch("src.cli.getTemplate", return_value=mock_template), \
         patch("src.cli.export_data", return_value=b"output data"), \
         patch("builtins.open", side_effect=open_side_effect):
        old_stderr = sys.stderr
        sys.stderr = captured_stderr = StringIO()
        try:
            exit_code = run(args)
        finally:
            sys.stderr = old_stderr

    stderr_output = captured_stderr.getvalue()

    assert exit_code == 0, f"Expected exit code 0, got {exit_code}"
    assert stderr_output == "", (
        f"Expected empty stderr in quiet mode, got: {stderr_output!r}"
    )
