/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/templates/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Packages
         * @description Return the list of available accounting package names.
         */
        get: operations["get_packages_api_templates_packages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/packages/{package}/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Templates
         * @description Return the list of available template names for a package.
         */
        get: operations["get_templates_api_templates_packages__package__templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/packages/{package}/templates/{template}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Template Detail
         * @description Return the full OutputTemplate for a given package and template.
         */
        get: operations["get_template_detail_api_templates_packages__package__templates__template__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documentation/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Documentation
         * @description Generate all 7 documentation artifacts from an ApplicationContext.
         */
        post: operations["generate_documentation_api_documentation_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Configurations
         * @description List all saved configurations.
         */
        get: operations["list_configurations_api_configurations_get"];
        put?: never;
        /**
         * Create Configuration
         * @description Create a new configuration.
         */
        post: operations["create_configuration_api_configurations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configurations/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Configuration
         * @description Get a configuration by name.
         */
        get: operations["get_configuration_api_configurations__name__get"];
        /**
         * Update Configuration
         * @description Update an existing configuration.
         */
        put: operations["update_configuration_api_configurations__name__put"];
        post?: never;
        /**
         * Delete Configuration
         * @description Delete a configuration by name.
         */
        delete: operations["delete_configuration_api_configurations__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApplicationContext
         * @description Generic context for the Documentation Module.
         *
         *     Each application module populates this with its domain-specific
         *     metadata. The Documentation Module depends only on this structure.
         */
        "ApplicationContext-Input": {
            /**
             * Applicationname
             * @default
             */
            applicationName: string;
            /**
             * Configurationname
             * @default
             */
            configurationName: string;
            /** Configurationdate */
            configurationDate?: string | null;
            sourceSystem?: components["schemas"]["SystemDescriptor"] | null;
            targetSystem?: components["schemas"]["SystemDescriptor"] | null;
            /**
             * Intermediarysystems
             * @default []
             */
            intermediarySystems: components["schemas"]["SystemDescriptor"][];
            /**
             * Processsteps
             * @default []
             */
            processSteps: components["schemas"]["ProcessStep"][];
            sourceDescription?: components["schemas"]["DataDescription"] | null;
            targetDescription?: components["schemas"]["DataDescription"] | null;
            transformDescription?: components["schemas"]["TransformDescriptor"] | null;
            controlTotals?: components["schemas"]["ControlTotals"] | null;
            /**
             * Userinstructionsteps
             * @default []
             */
            userInstructionSteps: string[];
        };
        /**
         * ApplicationContext
         * @description Generic context for the Documentation Module.
         *
         *     Each application module populates this with its domain-specific
         *     metadata. The Documentation Module depends only on this structure.
         */
        "ApplicationContext-Output": {
            /**
             * Applicationname
             * @default
             */
            applicationName: string;
            /**
             * Configurationname
             * @default
             */
            configurationName: string;
            /** Configurationdate */
            configurationDate?: string | null;
            sourceSystem?: components["schemas"]["SystemDescriptor"] | null;
            targetSystem?: components["schemas"]["SystemDescriptor"] | null;
            /**
             * Intermediarysystems
             * @default []
             */
            intermediarySystems: components["schemas"]["SystemDescriptor"][];
            /**
             * Processsteps
             * @default []
             */
            processSteps: components["schemas"]["ProcessStep"][];
            sourceDescription?: components["schemas"]["DataDescription"] | null;
            targetDescription?: components["schemas"]["DataDescription"] | null;
            transformDescription?: components["schemas"]["TransformDescriptor"] | null;
            controlTotals?: components["schemas"]["ControlTotals"] | null;
            /**
             * Userinstructionsteps
             * @default []
             */
            userInstructionSteps: string[];
        };
        /**
         * ArtifactContentType
         * @description Types of document artifacts.
         * @enum {string}
         */
        ArtifactContentType: "INPUT_DESCRIPTION" | "OUTPUT_DESCRIPTION" | "TRANSFORM_DESCRIPTION" | "USER_INSTRUCTION";
        /**
         * BalanceCheck
         * @description A reconciliation check in the control table.
         */
        BalanceCheck: {
            /** Description */
            description: string;
            /** Passed */
            passed: boolean;
        };
        /**
         * ColumnDescription
         * @description Describes a single column for documentation purposes.
         */
        ColumnDescription: {
            /** Name */
            name: string;
            /** Datatype */
            dataType: string;
            /** Description */
            description: string;
            /** Source */
            source: string;
        };
        /** ConfigurationListResponse */
        ConfigurationListResponse: {
            /** Configurations */
            configurations: components["schemas"]["CustomerConfiguration"][];
        };
        /**
         * ControlTable
         * @description Generated control table with reconciliation totals.
         */
        ControlTable: {
            /**
             * @default {
             *       "inputRowCount": 0,
             *       "outputRowCount": 0,
             *       "inputTotals": [],
             *       "outputTotals": [],
             *       "balanceChecks": []
             *     }
             */
            totals: components["schemas"]["ControlTotals"];
            /** Generatedat */
            generatedAt?: string | null;
        };
        /**
         * ControlTotals
         * @description Generic control totals for reconciliation.
         */
        ControlTotals: {
            /**
             * Inputrowcount
             * @default 0
             */
            inputRowCount: number;
            /**
             * Outputrowcount
             * @default 0
             */
            outputRowCount: number;
            /**
             * Inputtotals
             * @default []
             */
            inputTotals: components["schemas"]["NamedTotal"][];
            /**
             * Outputtotals
             * @default []
             */
            outputTotals: components["schemas"]["NamedTotal"][];
            /**
             * Balancechecks
             * @default []
             */
            balanceChecks: components["schemas"]["BalanceCheck"][];
        };
        /** CreateConfigurationRequest */
        CreateConfigurationRequest: {
            /** Name */
            name: string;
            /** Packagename */
            packageName: string;
            /** Templatename */
            templateName: string;
            /** Budgetcode */
            budgetcode: string;
            /** Year */
            year: number;
        };
        /** CustomerConfiguration */
        CustomerConfiguration: {
            /** Name */
            name: string;
            /** Packagename */
            packageName: string;
            /** Templatename */
            templateName: string;
            /** Budgetcode */
            budgetcode: string;
            /** Year */
            year: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * DataDescription
         * @description Describes a data structure (input or output) for documentation.
         */
        DataDescription: {
            /** Name */
            name: string;
            /**
             * Columns
             * @default []
             */
            columns: components["schemas"]["ColumnDescription"][];
            /**
             * Additionalnotes
             * @default
             */
            additionalNotes: string;
        };
        /**
         * DataType
         * @description Supported data types for column definitions.
         * @enum {string}
         */
        DataType: "STRING" | "INTEGER" | "FLOAT" | "BOOLEAN" | "DATE" | "DATETIME" | "NULL";
        /**
         * DiagramOutput
         * @description Generated diagram output.
         */
        DiagramOutput: {
            diagramType: components["schemas"]["DiagramType"];
            /**
             * Renderedcontent
             * @default
             */
            renderedContent: string;
            /**
             * Configurationref
             * @default
             */
            configurationRef: string;
            /** Generatedat */
            generatedAt?: string | null;
        };
        /**
         * DiagramType
         * @description Types of diagrams the documentation module can generate.
         * @enum {string}
         */
        DiagramType: "ARCHIMATE" | "BPMN";
        /**
         * DocumentArtifact
         * @description A generated documentation artifact.
         */
        DocumentArtifact: {
            /** Title */
            title: string;
            contentType: components["schemas"]["ArtifactContentType"];
            /**
             * Content
             * @default
             */
            content: string;
            /** Generatedat */
            generatedAt?: string | null;
        };
        /**
         * DocumentationPack
         * @description Complete set of 7 documentation artifacts.
         */
        DocumentationPack: {
            archimate?: components["schemas"]["DiagramOutput"] | null;
            bpmn?: components["schemas"]["DiagramOutput"] | null;
            inputDescription?: components["schemas"]["DocumentArtifact"] | null;
            outputDescription?: components["schemas"]["DocumentArtifact"] | null;
            transformDescription?: components["schemas"]["DocumentArtifact"] | null;
            controlTable?: components["schemas"]["ControlTable"] | null;
            userInstruction?: components["schemas"]["DocumentArtifact"] | null;
            applicationContext?: components["schemas"]["ApplicationContext-Output"] | null;
            /** Generatedat */
            generatedAt?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
            /**
             * Available Packages
             * @default []
             */
            available_packages: string[];
            /**
             * Available Templates
             * @default []
             */
            available_templates: string[];
        };
        /**
         * FixedNull
         * @description Always null placeholder.
         */
        FixedNull: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "fixed_null";
        };
        /**
         * FromSource
         * @description Maps from a source column.
         */
        FromSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "from_source";
            /** Sourcecolumnname */
            sourceColumnName: string;
        };
        /**
         * FromTransform
         * @description Computed during transformation (e.g., period extraction, DC split).
         */
        FromTransform: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "from_transform";
            /** Expression */
            expression: string;
        };
        /**
         * FromUserParam
         * @description Maps from a user-specified parameter.
         */
        FromUserParam: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "from_user_param";
            /** Paramname */
            paramName: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * NamedTotal
         * @description A labeled numeric total for control table use.
         */
        NamedTotal: {
            /** Label */
            label: string;
            /** Value */
            value: number;
        };
        /**
         * OutputTemplate
         * @description Target schema for a specific accounting package import format.
         */
        OutputTemplate: {
            /** Packagename */
            packageName: string;
            /** Templatename */
            templateName: string;
            /**
             * Columns
             * @default []
             */
            columns: components["schemas"]["TemplateColumnDef"][];
        };
        /** OutputTemplateResponse */
        OutputTemplateResponse: {
            template: components["schemas"]["OutputTemplate"];
        };
        /** PackageListResponse */
        PackageListResponse: {
            /** Packages */
            packages: string[];
        };
        /**
         * ProcessStep
         * @description A single step in the conversion process.
         */
        ProcessStep: {
            /** Stepnumber */
            stepNumber: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Actor */
            actor: string;
        };
        /**
         * SystemDescriptor
         * @description Describes a system involved in the conversion.
         */
        SystemDescriptor: {
            /** Name */
            name: string;
            /** Systemtype */
            systemType: string;
            /** Description */
            description: string;
        };
        /**
         * TemplateColumnDef
         * @description Definition of a single column in an output template.
         */
        TemplateColumnDef: {
            /** Name */
            name: string;
            dataType: components["schemas"]["DataType"];
            /** Nullable */
            nullable: boolean;
            /** Sourcemapping */
            sourceMapping: components["schemas"]["FromSource"] | components["schemas"]["FromUserParam"] | components["schemas"]["FromTransform"] | components["schemas"]["FixedNull"];
        };
        /** TemplateListResponse */
        TemplateListResponse: {
            /** Templates */
            templates: string[];
        };
        /**
         * TransformDescriptor
         * @description Describes the transformation logic for documentation.
         */
        TransformDescriptor: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Steps
             * @default []
             */
            steps: string[];
            /**
             * Generatedquery
             * @default
             */
            generatedQuery: string;
        };
        /** UpdateConfigurationRequest */
        UpdateConfigurationRequest: {
            /** Packagename */
            packageName?: string | null;
            /** Templatename */
            templateName?: string | null;
            /** Budgetcode */
            budgetcode?: string | null;
            /** Year */
            year?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ApplicationContext
         * @description Generic context for the Documentation Module.
         *
         *     Each application module populates this with its domain-specific
         *     metadata. The Documentation Module depends only on this structure.
         */
        ApplicationContext: {
            /**
             * Applicationname
             * @default
             */
            applicationName: string;
            /**
             * Configurationname
             * @default
             */
            configurationName: string;
            /**
             * Configurationdate
             * @default null
             */
            configurationDate: string | null;
            /** @default null */
            sourceSystem: components["schemas"]["SystemDescriptor"] | null;
            /** @default null */
            targetSystem: components["schemas"]["SystemDescriptor"] | null;
            /**
             * Intermediarysystems
             * @default []
             */
            intermediarySystems: components["schemas"]["SystemDescriptor"][];
            /**
             * Processsteps
             * @default []
             */
            processSteps: components["schemas"]["ProcessStep"][];
            /** @default null */
            sourceDescription: components["schemas"]["DataDescription"] | null;
            /** @default null */
            targetDescription: components["schemas"]["DataDescription"] | null;
            /** @default null */
            transformDescription: components["schemas"]["TransformDescriptor"] | null;
            /** @default null */
            controlTotals: components["schemas"]["ControlTotals"] | null;
            /**
             * Userinstructionsteps
             * @default []
             */
            userInstructionSteps: string[];
        };
        /** BoolVal */
        BoolVal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bool";
            /** Value */
            value: boolean;
        };
        /**
         * ColumnDef
         * @description Definition of a single column in a tabular dataset.
         */
        ColumnDef: {
            /** Name */
            name: string;
            dataType: components["schemas"]["DataType"];
            /**
             * Nullable
             * @default true
             */
            nullable: boolean;
        };
        /**
         * DataMetadata
         * @description Metadata attached to tabular data throughout the pipeline.
         */
        DataMetadata: {
            /**
             * Sourcename
             * @default
             */
            sourceName: string;
            /** @default EXCEL */
            sourceFormat: components["schemas"]["FileFormat"];
            /**
             * Importedat
             * @default null
             */
            importedAt: string | null;
            /**
             * Transformedat
             * @default null
             */
            transformedAt: string | null;
            /**
             * Exportedat
             * @default null
             */
            exportedAt: string | null;
            /**
             * Encoding
             * @default utf-8
             */
            encoding: string;
        };
        /**
         * FileFormat
         * @description Supported export file formats.
         * @enum {string}
         */
        FileFormat: "CSV" | "EXCEL";
        /**
         * DateVal
         * @description Date value stored as ISO 8601 string.
         */
        DateVal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "date";
            /** Value */
            value: string;
        };
        /**
         * DiagramTemplate
         * @description Base template for diagram generation.
         */
        DiagramTemplate: {
            templateType: components["schemas"]["DiagramType"];
            /**
             * Templatecontent
             * @default
             */
            templateContent: string;
            /**
             * Placeholders
             * @default []
             */
            placeholders: string[];
        };
        /** FloatVal */
        FloatVal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "float";
            /** Value */
            value: number;
        };
        /** IntVal */
        IntVal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "int";
            /** Value */
            value: number;
        };
        /**
         * MappingConfig
         * @description Column mapping configuration extracted from the Excel file.
         */
        MappingConfig: {
            /** Entitycolumn */
            entityColumn: string;
            /** Accountcolumn */
            accountColumn: string;
            /** Dccolumn */
            dcColumn: string;
            /**
             * Monthcolumns
             * @default []
             */
            monthColumns: components["schemas"]["MonthColumnDef"][];
        };
        /**
         * MonthColumnDef
         * @description Maps a source column to a budget period.
         */
        MonthColumnDef: {
            /** Sourcecolumnname */
            sourceColumnName: string;
            /** Periodnumber */
            periodNumber: number;
            /** Year */
            year: number;
        };
        /** NullVal */
        NullVal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "null";
        };
        /**
         * PDFMetadata
         * @description Metadata included in exported PDFs.
         */
        PDFMetadata: {
            /**
             * Screentitle
             * @default
             */
            screenTitle: string;
            /**
             * Configurationname
             * @default
             */
            configurationName: string;
            /**
             * Packagename
             * @default
             */
            packageName: string;
            /**
             * Templatename
             * @default
             */
            templateName: string;
            /**
             * Generatedat
             * @default null
             */
            generatedAt: string | null;
        };
        /**
         * Row
         * @description A single row of cell values.
         */
        Row: {
            /** Values */
            values: (components["schemas"]["StringVal"] | components["schemas"]["IntVal"] | components["schemas"]["FloatVal"] | components["schemas"]["BoolVal"] | components["schemas"]["DateVal"] | components["schemas"]["NullVal"])[];
        };
        /** StringVal */
        StringVal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "string";
            /** Value */
            value: string;
        };
        /**
         * TabularData
         * @description Internal representation of rows and columns with typed values.
         */
        TabularData: {
            /**
             * Columns
             * @default []
             */
            columns: components["schemas"]["ColumnDef"][];
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["Row"][];
            /**
             * Rowcount
             * @default 0
             */
            rowCount: number;
            /**
             * @default {
             *       "sourceName": "",
             *       "sourceFormat": "EXCEL",
             *       "importedAt": null,
             *       "transformedAt": null,
             *       "exportedAt": null,
             *       "encoding": "utf-8"
             *     }
             */
            metadata: components["schemas"]["DataMetadata"];
        };
        /**
         * UserParams
         * @description User-specified parameters per conversion run.
         */
        UserParams: {
            /** Budgetcode */
            budgetcode: string;
            /** Year */
            year: number;
        };
        /**
         * ValidationResult
         * @description Result of validating output data against a template.
         */
        ValidationResult: {
            /** Valid */
            valid: boolean;
            /**
             * Errors
             * @default []
             */
            errors: string[];
        };
        /**
         * ScreenContentType
         * @enum {string}
         */
        ScreenContentType: "SPREADSHEET" | "DIAGRAM" | "CONTROL_TABLE";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_packages_api_templates_packages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageListResponse"];
                };
            };
        };
    };
    get_templates_api_templates_packages__package__templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_detail_api_templates_packages__package__templates__template__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package: string;
                template: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputTemplateResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_documentation_api_documentation_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationContext-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentationPack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_configurations_api_configurations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationListResponse"];
                };
            };
        };
    };
    create_configuration_api_configurations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConfigurationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerConfiguration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_configuration_api_configurations__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerConfiguration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_configuration_api_configurations__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConfigurationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerConfiguration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_configuration_api_configurations__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
